# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sembly' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"


  # Firebase
  #use_frameworks!
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  pod 'react-native-maps', path: rn_maps_path

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'semblyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
