# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sembly' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sembly

  # Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  target 'semblyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end