# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sembly' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"


  # Firebase
  #use_frameworks!
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore', '~> 6.3.0'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-maps', path: rn_maps_path

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-fbsdk', :path => '../vendor/react-native-fbsdk'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  post_install do |installer|
    fix_fb
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  # post_install do |installer|
  #   fix_fb
  # end

  def fix_fb
      node_modules_path = '../node_modules'
      patched_text = File.read("./RCTFBSDKLoginButtonManager.m.patch")

      File.open("#{node_modules_path}/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m", "w") {|file| file.puts patched_text}
  end
  
  target 'semblyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
